# Autogenerated wrapper script for NCBIDatasets_jll for x86_64-w64-mingw32
export datasets

JLLWrappers.@generate_wrapper_header("NCBIDatasets")
JLLWrappers.@declare_executable_product(datasets)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        datasets,
        "bin\\datasets.exe",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
