# Autogenerated wrapper script for NCBIDatasets_jll for x86_64-linux-gnu
export datasets

JLLWrappers.@generate_wrapper_header("NCBIDatasets")
JLLWrappers.@declare_executable_product(datasets)
function __init__()
    JLLWrappers.@generate_init_header()
    JLLWrappers.@init_executable_product(
        datasets,
        "bin/datasets",
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
